---
- name: "Set host name"
  hostname:
    name="{{ ipa_fqdn }}"

- name: "Update /etc/hosts"
  lineinfile:
    dest="/etc/hosts"
    line="{{ ipa_ip }}  {{ ipa_fqdn }}  {{ ipa_hostname }}"

- name: "Set SELinux to permissive"
  selinux:
    policy="targeted"
    state="permissive"

- name: "Set primary & secondary DNS in network interface conf file"
  blockinfile:
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ network_interface_name }}"
    insertafter: "PEERDNS=no"
    block: |
      DNS1={{ primary_dns }}
      DNS2={{ secondary_dns }}
  notify: restart network

- name: "Install FreeIPA packages"
  yum:
    name="{{ item }}"
    state="present"
  with_items:
    - ipa-server
    - ipa-server-dns
    - bind-dyndb-ldap

- name: "Check if FreeIPA is already installed"
  stat:
    path="/root/cacert.p12"
  register: freeipa_status

- name: "Configure FreeIPA server"
  shell:
    "
    ipa-server-install \
    	--setup-dns \
    	--domain={{ domain_name }} \
    	--realm={{ ipa_realm }} \
    	--ds-password={{ ldap_directory_manager_password }} \
    	--admin-password={{ ipa_admin_password }} \
    	--forwarder={{ primary_dns }} \
      --forwarder={{ secondary_dns }} \
    	--reverse-zone={{ reverse_dns }} \
    	--unattended
    "
  when: freeipa_status.stat.exists == false

- name: "Start & Enable firewalld service"
  service:
    name="firewalld"
    state="started"
    enabled="yes"

- name: "Open needed ports in firewalld"
  firewalld:
    service="{{ item }}"
    permanent="yes"
    state="enabled"
    immediate="yes"
  with_items:
    - http
    - https
    - ldap
    - ldaps
    - kerberos
    - kpasswd
    - dns
    - ntp
