---
- name: "Enable use of cache-server"
  template:
    src="01proxy.j2"
    dest="/etc/apt/apt.conf.d/01proxy"
  when: use_cache_server == true

- name: "Upgrade packages"
  apt:
    update_cache="yes"
    upgrade="yes"
