---
- name: "Enable use of cache-server"
  template:
    src="01proxy.j2"
    dest="/etc/apt/apt.conf.d/01proxy"
  when: use_cache_server == true

- name: "Install dependencies"
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
  with_items:
    - python-apt
    - aptitude

- name: "Upgrade packages"
  apt:
    update_cache="yes"
    upgrade="yes"
