---
#TODO test avalability of cache-server
- name: Enable use of cache-server
  blockinfile:
    dest: /etc/yum.conf
    insertafter: "^distroverpkg=centos-release"
    block: "proxy=http://{{ cache_server_ip }}:{{ cache_server_port }}"
    state: present
  when: use_cache_server == true

- name: "Disable use of cache-server"
  blockinfile:
    dest: "/etc/yum.conf"
    block: "proxy=http://{{ cache_server_ip }}:{{ cache_server_port }}"
    state: absent
  when: use_cache_server == false
